dist: xenial
branches:
  except:
  - "/^M\\d-build\\.\\d*\\-\\d*$/"
services:
- postgresql
- xvfb
addons:
  postgresql: '9.4'
env:
- DJANGO_SETTINGS_MODULE="decide.travis_settings"
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install dbus-x11
- export DISPLAY=:99.0
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo cp chromedriver /usr/bin
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install flake8
script:
- cd decide
- coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
- coverage xml --fail-under 70
- python-codacy-coverage -r coverage.xml
- flake8 --select E501,E265,E225 . --exclude __pycache__,./*/migrations/,./decide/
before_deploy:
  if ! [ "$IS_TAGGED" ]; then
    export IS_TAGGED=1;
    git config --local user.name $USER_TRAVIS;
    git config --local user.email $EMAIL_TRAVIS;
    export YEAR=`date +"%Y"`;
    export GIT_TAG=M$MILESTONE_TRAVIS-build.$TRAVIS_BUILD_NUMBER-$YEAR;
    git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER";
  fi
deploy:
  - provider: releases
    api_key:
      secure: lHSsN/MBEymcPI/OopFvreP4LKbwiDZVA6+FWaa9dTsFbljht/2WM6wKigTQAgrnzw1ByHlq3TqUVgLS88to9vDcY/FYmJRAnCQJ9RaSj8pRbe1l94Vh52YwE82LIG5bBQ+k0bvwKxPp/m+mf/6WJihbp79dVXI2QsDXo4reMRKd6NMQu5t3dG6dyFoFwPtgpGGELeb+URUkFupLI1B2z4Liu/9KpzyJfXdzUi1S7ip7vPIw4QXbtQKBiKYSYTa0HDR/KIM3gLNywampijvpVCStJWEVqyjUpa/R6pCjGJDM1hDtsHnrdmhYOeSyoPgq6rOUbYYRLEKMMPy9on1OVYDhxUxbV09Y2C2j5twuDMDFaoWNTXoC+U3bgw/57xtSQrH+2v9XrkPb/zss5I0KL1902IlEYpFzSq7UbxrL7msKBVXDDBp9zr/DdkZPnrSNJZbBCqsjC8xj3pp6DWPx5BLxE/NlmM1xt1LZeVEskrqV0qsEY+QEe0hZgWCnWYkOfIBQRvvLw/ls0jjomOG4P7EHA8EUYT1lZXbfPNrWlvd93+vvH5tzt5rhBRv5fX4RRE5ObxE+LfhaYn8ylvNbul+ojtE5iKeRXYaRBFh+MvFno7Y0sbcxDnmAdXGxMZuHG6yHzATZi9rf6p6HMgrfmHLFh/2Nlu3oLdMfuqUcn0s=
    file: "$NOMBRE_ZIP.zip"
    on:
      branch: master
      repo: antnolang/decide
  - provider: heroku
    app: "decide-dialga-votacion-m4"
    strategy: git
    api_key:
      secure: "NT+wo/WcahBPYEOBlmDs1aeUjfRCwSGuDTPK9uK18l5iJ4DWbYyYNnJrfkjG/qF/hJdSsEpu5vWaGI6bl7OrrVkKA9XRlj0g7iKaqOYvy30lGNH+hSWy75eMrjSntdV6H7BZpjzmCpRYn14Qcq9Ows1PS8d+AuuY8tQsSJP9NcDur7CTzc9wqYTKtocreez3Gmel7czoeiUgocBH56/GSEXI8h7v8cB4TLyCyW6jj2HnWjEAx66nueOa8QhBALfojKoOVxA5w8FldXvwP0nyMoF+fmO3WJd6cc6fYM11l+jPAtgfD1gOPOfKAVti2y2PrgJ7pY0uRDLeyUtj5MlY+8Q9BldZzDrh1qBzfWbhj4bEQMJ01IYAKe2xhE8vZzQ/1zWVqSlITWsjsozsYqN8sn8eDl/5zqGiOvBCX3D5WDQ5ubBY8iejw7Y3vbpzwCHJGjA9Q3k6mQAIjJ99pZH8gBAknOPeyEg2cxNtaabEPHpF6fc1SmGXUbw4wefAEnbn09To0BhB2HzU82tSK7U19VNMmtkVNh/gGQ3qVRfC4hvk8TXxsg6qbKWLcPymo2gogpQ2n1JMZLnPclTQS0rTuJTcV4pTrgtb7J5W3UjunIri66RzDsSgxemtrZMxz/Q/HZoWYipHr8ZXzl4E6u3HJQSKdL4u9qXT+LOA+orfkYs="
    on:
      branch: master
      repo: antnolang/decide
