dist: xenial
branches:
  except:
  - "/^M\\d-build\\.\\d*\\-\\d*$/"
services:
- postgresql
- xvfb
addons:
  postgresql: '9.4'
env:
- DJANGO_SETTINGS_MODULE="decide.travis_settings"
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install dbus-x11
- export DISPLAY=:99.0
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo cp chromedriver /usr/bin
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install flake8
script:
- cd decide
- coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
- coverage xml --fail-under 70
- python-codacy-coverage -r coverage.xml
- flake8 --select E501,E265,E225 . --exclude __pycache__,./*/migrations/,./decide/
before_deploy:
  if ! [ "$IS_TAGGED" ]; then
    export IS_TAGGED=1;
    git config --local user.name $USER_TRAVIS;
    git config --local user.email $EMAIL_TRAVIS;
    export YEAR=`date +"%Y"`;
    export GIT_TAG=M$MILESTONE_TRAVIS-build.$TRAVIS_BUILD_NUMBER-$YEAR;
    git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER";
  fi
deploy:
  - provider: releases
    api_key:
      secure: lHSsN/MBEymcPI/OopFvreP4LKbwiDZVA6+FWaa9dTsFbljht/2WM6wKigTQAgrnzw1ByHlq3TqUVgLS88to9vDcY/FYmJRAnCQJ9RaSj8pRbe1l94Vh52YwE82LIG5bBQ+k0bvwKxPp/m+mf/6WJihbp79dVXI2QsDXo4reMRKd6NMQu5t3dG6dyFoFwPtgpGGELeb+URUkFupLI1B2z4Liu/9KpzyJfXdzUi1S7ip7vPIw4QXbtQKBiKYSYTa0HDR/KIM3gLNywampijvpVCStJWEVqyjUpa/R6pCjGJDM1hDtsHnrdmhYOeSyoPgq6rOUbYYRLEKMMPy9on1OVYDhxUxbV09Y2C2j5twuDMDFaoWNTXoC+U3bgw/57xtSQrH+2v9XrkPb/zss5I0KL1902IlEYpFzSq7UbxrL7msKBVXDDBp9zr/DdkZPnrSNJZbBCqsjC8xj3pp6DWPx5BLxE/NlmM1xt1LZeVEskrqV0qsEY+QEe0hZgWCnWYkOfIBQRvvLw/ls0jjomOG4P7EHA8EUYT1lZXbfPNrWlvd93+vvH5tzt5rhBRv5fX4RRE5ObxE+LfhaYn8ylvNbul+ojtE5iKeRXYaRBFh+MvFno7Y0sbcxDnmAdXGxMZuHG6yHzATZi9rf6p6HMgrfmHLFh/2Nlu3oLdMfuqUcn0s=
    file: "$NOMBRE_ZIP.zip"
    on:
      branch: master
      repo: antnolang/decide
  - provider: heroku
    app: "decide-dialga-votacion-m4"
    strategy: git
    api_key:
      secure: DF0FTrUoqm0bCIaoabe+E851l8LRt6n05IGaUp01+UBIKxRnwEIItzj7Te6IOUBstjWutyvMV/gOpKspzakJIyVPNJFJCTxCa6RnMCW37KXOzWnVS6e52I0doqpVI1tMrdktuJvMMHlIsvBtSL1B7vltop/N4UsHbiAupZ4aAyoP4pPwDjlTPNVcZGnrVtBo1BhGgtGtfhnN2zz40SQ1Wnf0ISfrMhqqVHGWy65oZCS2sZSPI9I+Dazxpyuo2rBbp5s7GWNI3etpGhNMi8wpJJ7NH5kY8sZGUGPYc0u+cGVVntxOmLuvXPynaU2yRNKnfn+tcMmKsWeygbXE8ACVToXpGfwWlo3CZWjz/SdtQWC9eq1DiTnr9mIqg6NUPIVSvxpJ61eCRRDvm3EIbVa1gOxiJFgBGo5juglgqTSjF27V4+gipzrXVptI9uzfTlfveMYEM3WN5WX+DCa5Y5IYuPP9iMotRdH4VBBiy0jnUAb7SOI8hN+Wo2LgJkQLDKtOKcVb1UbqNkEwR8Xaq1EM1zqVtECtDDjc06YgbO/UHJZLyigMHQwETOBaNjxgIJQBOITGHPJkybN0XGaBhHovXWvZaQSSRGQQyMgnBcy6YDko2a98AtnNYtyG9z//NUYzS3OP1ZmiOcaz63EMAcLub826z9GRVTjMVFd+wam47D8=
    on:
      branch: master
      repo: antnolang/decide
