# Generated by Django 2.0 on 2020-01-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200126_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
